### ISSUE TITLE
Windows - Error: Tried loading "src/generate.js"

### ISSUE THREAD

**Issue by mahnunchik** [rejas/gulp-modernizr#23]
Hi,

I've tried to run my `gulp-modernizr` task on Windows. I got the error.
On Linux/Mac task working normally.

```
C:\project>gulp modernizr
[06:07:25] Using gulpfile C:\project\gulpfile.js
[06:07:25] Starting 'modernizr'...
C:\project\node_modules\gulp-modernizr\node_modules\custom
izr\node_modules\modernizr\node_modules\requirejs\bin\r.js:2559
                    throw err;
                          ^
Error: Tried loading "src/generate.js" at src/generate.js then tried node's require("src/generate.js") and it failed with error: Error: Cannot find module 'src/generate.js'
    at C:\project\node_modules\gulp-modernizr\node_modules\customizr\node_modules\modernizr\node_modules\requirejs\bin\r.js:2552:27
    at Object.context.execCb (C:\project\node_modules\gulp-modernizr\node_modules\customizr\node_modules\modernizr\node_modules\requirejs\bin\r.js:1916:33)
    at Object.Module.check (C:\project\node_modules\gulp-modernizr\node_modules\customizr\node_modules\modernizr\node_modules\requirejs\bin\r.js:1125:51)
    at Object.Module.enable (C:\project\node_modules\gulp-modernizr\node_modules\customizr\node_modules\modernizr\node_modules\requirejs\bin\r.js:1409:22)
    at Object.context.enable (C:\project\node_modules\gulp-modernizr\node_modules\customizr\node_modules\modernizr\node_modules\requirejs\bin\r.js:1777:39)
    at Function.req.get (C:\project\node_modules\gulp-modernizr\node_modules\customizr\node_modules\modernizr\node_modules\requirejs\bin\r.js:2476:33)
    at Object.localRequire [as require] (C:\project\node_modules\gulp-modernizr\node_modules\customizr\node_modules\modernizr\node_modules\requirejs\bin\r.js:1650:40)
    at requirejs (C:\project\node_modules\gulp-modernizr\node_modules\customizr\node_modules\modernizr\node_modules\requirejs\bin\r.js:2003:24)
    at Object.<anonymous> (C:\project\node_modules\gulp-modernizr\node_modules\customizr\node_modules\modernizr\lib\build.js:123:18)
    at Module._compile (module.js:460:26)

C:\project>
```

Task:

``` js
gulp.task( 'modernizr', function () {
  return gulp.src( ['path/to/*.css', 'path/to/*js'] )
    .pipe( $.modernizr( 'modernizr-build.js', {
      options : [
        'setClasses'
      ]
    } ) )
    .pipe( gulp.dest( paths.scripts.dist ) );
});
```

Windows 7 32bit
NodeJS 0.10 - 0.12

Dependency versions:

```
├─┬ gulp-modernizr@1.0.0-alpha
│ ├─┬ customizr@1.0.0-alpha
│ │ ├── colors@0.6.2
│ │ ├── deep-equal@0.1.2
│ │ ├─┬ glob@3.2.11
│ │ │ ├── inherits@2.0.1
│ │ │ └─┬ minimatch@0.3.0
│ │ │   ├── lru-cache@2.5.0
│ │ │   └── sigmund@1.0.0
│ │ ├── mkdirp@0.3.5
│ │ ├─┬ modernizr@3.0.0-alpha
│ │ │ ├── file@0.2.2
│ │ │ ├── lodash@3.1.0
│ │ │ ├── marked@0.2.10
│ │ │ ├── mkdirp@0.3.5
│ │ │ ├── requirejs@2.1.16
│ │ │ └─┬ yargs@2.3.0
│ │ │   └── wordwrap@0.0.2
│ │ ├─┬ nopt@2.1.2
│ │ │ └── abbrev@1.0.5
│ │ ├─┬ optimist@0.6.1
│ │ │ ├── minimist@0.0.10
│ │ │ └── wordwrap@0.0.2
│ │ ├── promised-io@0.3.4
│ │ ├── underscore@1.5.2
│ │ └── win-spawn@2.0.0
│ ├─┬ grunt-legacy-log@0.1.1
│ │ ├── colors@0.6.2
│ │ ├── hooker@0.2.3
│ │ ├── lodash@2.4.1
│ │ └── underscore.string@2.3.3
│ ├─┬ gulp-util@2.2.20
│ │ ├─┬ chalk@0.5.1
│ │ │ ├── ansi-styles@1.1.0
│ │ │ ├── escape-string-regexp@1.0.2
│ │ │ ├─┬ has-ansi@0.1.0
│ │ │ │ └── ansi-regex@0.2.1
│ │ │ ├─┬ strip-ansi@0.3.0
│ │ │ │ └── ansi-regex@0.2.1
│ │ │ └── supports-color@0.2.0
│ │ ├─┬ dateformat@1.0.11
│ │ │ ├── get-stdin@4.0.1
│ │ │ └─┬ meow@3.0.0
│ │ │   ├─┬ camelcase-keys@1.0.0
│ │ │   │ ├── camelcase@1.0.2
│ │ │   │ └── map-obj@1.0.0
│ │ │   ├─┬ indent-string@1.2.0
│ │ │   │ ├── get-stdin@3.0.2
│ │ │   │ └─┬ repeating@1.1.1
│ │ │   │   ├── is-finite@1.0.0
│ │ │   │   └── meow@2.1.0
│ │ │   ├── minimist@1.1.0
│ │ │   └── object-assign@2.0.0
│ │ ├── lodash._reinterpolate@2.4.1
│ │ ├─┬ lodash.template@2.4.1
│ │ │ ├── lodash._escapestringchar@2.4.1
│ │ │ ├─┬ lodash.defaults@2.4.1
│ │ │ │ └── lodash._objecttypes@2.4.1
│ │ │ ├─┬ lodash.escape@2.4.1
│ │ │ │ ├─┬ lodash._escapehtmlchar@2.4.1
│ │ │ │ │ └── lodash._htmlescapes@2.4.1
│ │ │ │ └─┬ lodash._reunescapedhtml@2.4.1
│ │ │ │   └── lodash._htmlescapes@2.4.1
│ │ │ ├─┬ lodash.keys@2.4.1
│ │ │ │ ├── lodash._isnative@2.4.1
│ │ │ │ ├─┬ lodash._shimkeys@2.4.1
│ │ │ │ │ └── lodash._objecttypes@2.4.1
│ │ │ │ └─┬ lodash.isobject@2.4.1
│ │ │ │   └── lodash._objecttypes@2.4.1
│ │ │ ├── lodash.templatesettings@2.4.1
│ │ │ └── lodash.values@2.4.1
│ │ ├── minimist@0.2.0
│ │ ├─┬ multipipe@0.1.2
│ │ │ └─┬ duplexer2@0.0.2
│ │ │   └─┬ readable-stream@1.1.13
│ │ │     ├── core-util-is@1.0.1
│ │ │     ├── inherits@2.0.1
│ │ │     ├── isarray@0.0.1
│ │ │     └── string_decoder@0.10.31
│ │ ├─┬ through2@0.5.1
│ │ │ ├─┬ readable-stream@1.0.33
│ │ │ │ ├── core-util-is@1.0.1
│ │ │ │ ├── inherits@2.0.1
│ │ │ │ ├── isarray@0.0.1
│ │ │ │ └── string_decoder@0.10.31
│ │ │ └── xtend@3.0.0
│ │ └─┬ vinyl@0.2.3
│ │   └── clone-stats@0.0.1
│ └─┬ through2@0.4.2
│   ├─┬ readable-stream@1.0.33
│   │ ├── core-util-is@1.0.1
│   │ ├── inherits@2.0.1
│   │ ├── isarray@0.0.1
│   │ └── string_decoder@0.10.31
│   └─┬ xtend@2.1.2
│     └── object-keys@0.4.0
```

**Comment by owanturist** [comment]
:+1:

**Comment by jon64digital** [comment]
Same here :(

**Comment by rejas** [comment]
Hi @mahnunchik @owanturist @jon64digital is this still an issue for you with the newest version (2.0.0) or did you already move on?

**Comment by mahnunchik** [comment]
I don't have windows now 😭

**Comment by rejas** [comment]
Is this that bad? ;-)
